import logging

from biothings.web.handlers import MetadataSourceHandler
from tornado.web import RequestHandler


class WebAppHandler(RequestHandler):
    def get(self):
        if self.render("dist/index.html"):
            self.render("dist/index.html")
        else:
            logging.info("Unable to find dist folder from react app.")


class NDESourceHandler(MetadataSourceHandler):
    """
    GET /v1/metadata
    """

    def extras(self, _meta):
        source_info = {
            # Example Object
            # <SOURCE_NAME> = https://api.data.niaid.nih.gov/v1/metadata
            # <SOURCE_NAME> = {
            #       'name': 'A proper source name',
            #       'description': 'A short description of what the source offers, usually found on the source's about page',
            #       'schema': 'A dict where the key is their metadata variable and the value is our transformation. Ex: {"summary":"description"},
            #       'url': 'The source's URL',
            #       'identifier':'includedInDataCatalog.name',
            # }
            "dryad": {
                "name": "Dryad Digital Repository",
                "description": "Dryad Digital Repository is a GREI repository that includes most data types and domains.",
                "schema": {
                    "name": "name",
                    "description": "description",
                    "contentUrl": "contentUrl",
                    "identifier": "identifier, doi",
                    "keywords": "keywords",
                    "creator": "author",
                    "distribution": "distribution",
                    "temporalCoverage": "temporalCoverage",
                    "spatialCoverage": "spatialCoverage",
                    "citation": "citation",
                    "license": "license",
                    "datePublished": "datePublished",
                    "conditions": "healthCondition.name",
                    "outcomeNames": "variable_measured",
                    "digitalObjectId": "doi",
                    "studyMetadataDoi": "doi",
                    "extractedBriefSummary": "description",
                    "draftCreatedDate": "dateCreated",
                    "postedDate": "datePublished",
                    "updatedDate": "dateModified",
                },
                "url": "https://datadryad.org",
                "identifier": "Dryad Digital Repository",
            },
            "vivli": {
                "name": "Vivli",
                "description": "Vivli is a GREI repository that includes most data types and domains.",
                "schema": {
                    "nctId": "identifer",
                    "secondaryIds": "identifier",
                    "registryInfo": "sdPublishers",
                    "principalInvestigator": "author",
                    "studyTitle": "name",
                    "leadSponsor": "funding",
                    "collaborators": "funding",
                    "studyStartDate": "temporalInterval.startDate",
                    "actualStudyCompletionDate": "temporalInterval.endDate",
                    "locationsOfStudySites": "spatialCoverage",
                    "phase": "keywords",
                    "studyType": "keywords",
                    "conditions": "healthCondition.name",
                    "outcomeNames": "variable_measured",
                    "digitalObjectId": "doi",
                    "studyMetadataDoi": "doi",
                    "extractedBriefSummary": "description",
                    "draftCreatedDate": "dateCreated",
                    "postedDate": "datePublished",
                    "updatedDate": "dateModified",
                },
                "url": "https://vivli.org/",
                "identifier": "Vivli",
            },
            "ncbi_pmc": {
                "name": "NCBI PMC",
                "description": "PubMed Central® (PMC) is a free full-text archive of biomedical and life sciences journal literature at the U.S. National Institutes of Health's National Library of Medicine (NIH/NLM). In keeping with NLM's legislative mandate to collect and preserve the biomedical literature, PMC is part of the NLM collection, which also includes NLM's extensive print and licensed electronic journal holdings and supports contemporary biomedical and health care research and practice as well as future scholarship. Available to the public online since 2000, PMC was developed and is maintained by the National Center for Biotechnology Information(NCBI) at NLM.",
                "schema": {
                    "article-id": "identifer",
                    "article-id": "url",
                    "volume": "citation.volume",
                    "journal-title": "citation.journalName",
                    "pub-date": "citation.datePublished",
                    "article-title": "citation.name",
                    "article-id": "citation.pmid",
                    "article-id": "citation.identifier",
                    "article-id": "citation.url",
                    "article-id": "citation.doi",
                    "abstract": "description",
                    "contrib": "author",
                },
                "url": "https://www.ncbi.nlm.nih.gov/pmc/",
                "identifier": "NCBI PMC",
            },
            "veupathdb": {
                "name": "VEuPathDB",
                "description": "The Eukaryotic Pathogen, Vector and Host Informatics Resource (VEuPathDB) is a NIAID supported IID repository that includes genomic and phenotypic data for eukaryotic pathogens and invertebrate vectors of infectious disease.",
                "schema": {
                    "id": "identifer",
                    "displayName": "name",
                    "contact_name": "author",
                    "summary": "description",
                    "type": "measurementTechnique",
                    "sdPublisher": "project_id",
                    "short_attribution": "creditText",
                    "release_policy": "conditionOfAccess",
                    "version": "dateModified",
                    "author": "affiliation",
                    "GenomeHistory": "dateUpdated",
                    "Version": "datePublished",
                    "organism": "species",
                    "HyperLinks": "distribution",
                    "gene_count": "variableMeasured",
                    "gene_type": "GeneTypeCounts",
                },
                "url": "https://veupathdb.org/veupathdb/app/",
                "identifier": "VEuPathDB",
            },
            "acd_niaid": {
                "name": "AccessClinicalData@NIAID",
                "description": "AccessClinicalData is a NIAID supported IID repository that includes clinical trials data.",
                "schema": {
                    "title": "name",
                    "cmc_unique_id": "identifier",
                    "brief_summary": "description",
                    "data_availability_date": "datePublished",
                    "most_recent_update": "dateModified",
                    "data_available": "additionalType",
                    "creator": "funding.funder.name",
                    "nct_number": "nctid, identifier",
                    "condition": "healthCondition",
                    "clinical_trial_website": "mainEntityOfPage",
                    "publications": "citation",
                    "data_available_for_request": "conditionsOfAccess",
                },
                "url": "https://accessclinicaldata.niaid.nih.gov/",
                "identifier": "AccessClinicalData@NIAID",
            },
            "sb_apps": {
                "name": "Seven Bridges Public Apps Gallery",
                "description": "The Seven Bridges Public Apps Gallery offers a repository of publicly available apps suitable for many different types of data analysis. Apps include both tools (individual bioinformatics utilities) and workflows (chains or pipelines of connected tools). The publicly available apps are maintained by the Seven Bridges Platform bioinformatics team to represent the latest tool versions.",
                "schema": {
                    "class": "applicationCategory",
                    "label": "name",
                    "description": "description",
                    "inputs": "input",
                    "outputs": "output",
                    "requirements": "softwareRequirements",
                    "sbg:image_url": "thumbnailUrl",
                    "sbg:toolkit": "applicationSuite",
                    "sbg:license": "license",
                    "sbg:links": "codeRepository",
                    "sbg:categories": "applicationSubCategory",
                    "sbg:toolAuthor": "author",
                    "sbg:appVersion": "softwareVersion",
                    "sbg:id": "url, identifier",
                    "sbg:revisionNotes": "version",
                    "sbg:modifiedOn": "dateModified",
                    "sbg:createdOn": "dateCreated",
                    "sbg:contributors": "contributor",
                    "sbg:publisher": "sdPublisher",
                    "sbg:workflowLanguage": "programmingLanguage",
                },
                "url": "https://workspace.niaiddata.org/public/apps",
                "identifier": "PublicApps@SevenBridges",
            },
            "zenodo": {
                "name": "Zenodo",
                "description": "Zenodo is a GREI repository that includes most data types and domains.",
                "schema": {
                    "title": "name",
                    "header": "dateModifed, url",
                    "description": "description",
                    "date": "datePublished",
                    "language": "inLanguage.name",
                    "subject": "keywords",
                    "relatedIdentifier": "topicCategory",
                    "xml[DOI]": "doi",
                    "xml[resourceTypeGeneral]": "@type",
                    "xml[creator][creatorName]": "author.name",
                    "xml[creator][affiliation]": "author.affiliation",
                    "xml[creator][nameIdentifier]": "author.identifier",
                    "xml[rights]": "conditionsOfAccess, license",
                    "xml[relatedIdentifier][relationType]": "citedBy",
                    "xml[contributor][contributorName]": "funding.funder.name",
                },
                "url": "https://zenodo.org/",
                "identifier": "Zenodo",
            },
            "dde": {
                "name": "Data Discovery Engine",
                "description": "The Data Discovery Engine is a NIAID supported metadata registry that includes metadata from IID and general repositories.",
                "schema": {
                    "creator": "author",
                    "_id": "identifier",
                    "date_created": "dateCreated",
                    "last_updated": "dateModifed",
                    "@type": "@type",
                    "measurementTechnique": "measurementTechnique",
                    "infectiousAgent": "infectiousAgent",
                    "infectiousDisease": "infectiousDisease",
                    "species": "species",
                },
                "url": "https://discovery.biothings.io/",
                "identifier": "Data Discovery Engine",
            },
            "ncbi_geo": {
                "name": "NCBI GEO",
                "description": "Gene Expression Omnibus (GEO) is an NIH supported repository that includes microarray and next-generation sequencing data for high-throughput functional genomics for most domains.",
                "schema": {
                    "_id": "identifier",
                    "contributor(s)": "author",
                    "organization": "publisher",
                    "title": "name",
                    "organism": "species",
                    "experiment type": "measurementTechnique",
                    "summary": "description",
                    "submission date": "datePublished",
                    "last update date": "dateModified",
                    "citation(s)": "citation",
                },
                "url": "https://www.ncbi.nlm.nih.gov/geo/",
                "identifier": "NCBI GEO",
            },
            "immport": {
                "name": "ImmPort",
                "description": "The Immunology Database and Analysis Portal (ImmPort) is a NIAID supported IID repository that includes multimodal immunological data.",
                "schema": {
                    "_id": "identifer",
                    "creator": "author",
                    "citations": "citedBy",
                    "identifers": "identifer",
                    "species": "species",
                    "measurementTechnique": "measurementTechnique",
                    "distribution": "distribution",
                    "includedInDataCatalog": "includedInDataCatalog",
                    "date": "date",
                },
                "url": "https://www.immport.org/shared/home",
                "identifier": "ImmPort",
            },
            "omicsdi": {
                "name": "OmicsDI",
                "description": "Omics Discovery Index (OmicsDI) is a generalist repository that is part of ELIXIR infrastructure that includes multi-omics data for most domains.",
                "schema": {
                    "_id": "identifer",
                    "citation": "citation",
                    "creator": "author",
                    "description": "description",
                    "distribution": "distribution",
                    "keywords": "keywords",
                    "name": "name",
                    "sameAs": "sameAs",
                    "variableMeasured": "variableMeasured",
                },
                "url": "https://www.omicsdi.org/",
                "identifier": "Omics Discovery Index (OmicsDI)",
            },
            "mendeley": {
                "name": "Mendeley Data",
                "description": "Mendeley Data is a GREI repository that includes most data types and domains.",
                "schema": {
                    "id": "identifer",
                    "doi": "doi",
                    "name": "name",
                    "description": "description",
                    "contributors": "contributors",
                    "files": "distribution",
                    "articles": "citation",
                    "categories": "keywords",
                    "publish_date": "datePublished",
                    "related_links": "citation",
                    "modified_on": "dateModified",
                    "links": "url",
                    "repository": "sdPublisher",
                },
                "url": "https://data.mendeley.com/",
                "identifier": "Mendeley",
            },
            "reframedb": {
                "name": "ReframeDB",
                "description": "ReframeDB is a Calibr maintained repository that has a screening set of 12,000 compounds for drug repositioning.",
                "schema": {
                    "assay_id": "identifer",
                    "assay_title": "name",
                    "title_short": "alternateName",
                    "authors": "author",
                    "summary": "description",
                    "purpose": "description",
                    "protocol": "description",
                    "readout": "description",
                    "detection_method": "description",
                    "detection_reagents": "description",
                    "components": "description",
                    "drug_conc": "description",
                    "indication": "healthCondition",
                    "assay_type": "measurementTechnique",
                    "bibliography": "citation",
                },
                "url": "https://reframedb.org/",
                "identifier": "ReframeDB",
            },
            "clinepidb": {
                "description": "ClinEpiDB is a NIAID supported IID repository that includes epidemiological data.",
                "identifier": "ClinEpiDB",
                "name": "ClinEpiDB",
                "schema": {
                        "Study_Design": "measurementTechnique",
                        "description": "description",
                        "summary": "description",
                        "WHO": "keywords",
                        "Participant_Type": "keywords",
                        "Country": "spatialCoverage",
                        "study_access": "conditionOfAccess",
                        "Years": "temporalCoverage",
                        "disease": "healthCondition",
                        "Publications": "citation",
                        "release_date": "distribution.dateModified",
                        "dataset_name": "distribution.name",
                        "contact_name": "author.name",
                        "Contacts": "affiliation",
                        "HyperLinks": "isBasedOn.url"
                },
                "url": "https://clinepidb.org/ce/app",
            },
            "lincs": {
                "description": "The Library of Integrated Network-Based Cellular Signatures (LINCS) Data Portal is an NIH supported repository that includes gene expression and other cellular processes data.",
                "identifier": "LINCS",
                "name": "BD2K-LINCS DCIC",
                "schema": {
                    "centerdatasetid": "url",
                    "funding": "funding",
                    "assayoverview": "description",
                    "centerurl": "author.url",
                    "description": "description",
                    "principalinvestigator": "author.name",
                    "centerfullname": "author.affiliation",
                    "datemodified": "dateUpdated",
                    "screeninglabinvestigator": "author.name",
                    "datasetname": "name",
                    "datasetid": "identifier",
                    "datereleased": "datePublished",
                    "assayname": "measurementTechnique",
                    "assayformat": "measurementTechnique",
                    "assaydesignmethod": "keywords",
                    "physicaldetection": "variableMeasured",
                    "biologicalprocess": "keywords",
                    "technologies": "keywords",
                    "biologicalbucket": "keywords",
                    "endpointcategorization": "keywords",
                    "size": "distribution.contentSize",
                    "datasetgroup": "isRelatedTo",
                    "toollink": "isBasedOn",
                    "tool": "isBasedOn",
                    "protocol": "isBasedOn.url",
                    "protein": "keywords"
                },
                "url": "https://lincsportal.ccs.miami.edu/",
            },
            "dataverse": {
                "description": "Harvard Dataverse is a GREI repository that includes most data types and domains.",
                "identifier": "Harvard Dataverse",
                "name": "Harvard Dataverse",
                "schema": {
                    "@context": "@context",
                    "@type": "@type",
                    "identifier": ["url", "doi", "identifier"],
                    "name": "name",
                    "creator": "author",
                    "author": "author",
                    "datePublished": "datePublished",
                    "dateModified": "dateModified",
                    "description": "description",
                    "keywords": "keywords",
                    "citation": "citation.citation",
                    "license": "license",
                    "includedInDataCatalog": "includedInDataCatalog",
                    "publisher": "sdPublisher",
                    "funder": "funder",
                    "distribution": "distribution",
                    "type": "@type",
                    "global_id": "doi",
                    "published_at": "datePublished",
                    "identifier_of_dataverse": "sdPublisher.identifier",
                    "name_of_dataverse": "sdPublisher.name",
                    "subjects": "topicCategory",
                    "createdAt": "dateCreated",
                    "updatedAt": "dateModified",
                    "authors": "author.name"

                },
                "url": "https://dataverse.harvard.edu/",
            },
            "hubmap": {
                "description": "The Human BioMolecular Atlas Program (HuBMAP) is an NIH supported repository that includes multimodal data of healthy cells in the human body.",
                "identifier": "HuBMAP",
                "name": "HuBMAP",
                "schema": {
                    "hubmap_id": "name",
                    "title": "description",
                    "anatomy_0": "keywords",
                    "anatomy_1": "keywords",
                    "anatomy_2": "keywords",
                    "display_subtype": "keywords",
                    "contacts.affiliation": "author.affiliation",
                    "contacts.first_name": "author.givenName",
                    "contacts.last_name": "author.familyName",
                    "contacts.middle_name_or_initial": "author.givenName",
                    "contacts.name": "author.name",
                    "contacts.orcid_id": "author.identifier",
                    "contributors.affiliation": "author.affiliation",
                    "contributors.first_name": "author.givenName",
                    "contributors.last_name": "author.familyName",
                    "contributors.middle_name_or_initial": "author.givenName",
                    "contributors.name": "author.name",
                    "contributors.orcid_id": "author.identifier",
                    "created_timestamp": "dateCreated",
                    "last_modified_timestamp": "dateModified",
                    "published_timestamp": "datePublished",
                    "data_access_level": "isAccessibleForFree",
                    "data_types": "measurementTechnique.name",
                    "dataset_info": "measurementTechnique.description",
                    "doi_url": "doi",
                    "uuid": "url",
                    "file.description": "distribution.name",
                    "file.mapped_description": "distribution.description",
                    "file.rel_path": "distribution.contentUrl",
                    "file.size": "distribution.contentSize",
                    "file.type": "distribution.encodingFormat",
                    "version": "version",
                    "metadata.dag_provenance_list": "isBasedOn.name",
                    "metadata.protocols_io_doi": "isBasedOn.doi"
                },
                "url": "https://hubmapconsortium.org/",
            },
            "ncbi_sra": {
                "description": "Sequence Read Archive (SRA) is the NIH supported largest publicly available repository of high throughput sequencing data that includes raw sequencing data and alignment information for most domains.",
                "identifier": "NCBI SRA",
                "name": "NCBI SRA",
                "schema": {
                    "Accession": "url",
                    "Updated": "dateModified",
                    "Published": "datePublished",
                    "Recieved": "dateCreated",
                    "Visibility": "conditionsOfAccess",
                    "ReplacedBy": "sameAs",
                    "study_title": "name",
                    "study_abstract": "description",
                    "contact_name": "author",
                    "GCP_url": "contentUrl",
                    "GCP_free_egress": "isAccessibleForFree",
                    "AWS_url": "contentUrl",
                    "AWS_free_egress": "isAccessibleForFree",
                    "organism_taxid": "species.identifier",
                    "organism_name": "species.name",
                    "run_accession": "isBasedOn.identifier",
                    "BioProject": "isBasedOn.identifier",
                    "experiment_accession": "isBasedOn.identifier",
                    "sample_accession": "isBasedOn.identifier",
                    "instrument": "isBasedOn.identifier",
                    "cell line": "isBasedOn.identifier",
                    "HapMap sample ID": "isBasedOn.identifier"

                },
                "url": "https://www.ncbi.nlm.nih.gov/sra",
            },
            "vdj": {
                "description": "VDJServer is a NIAID supported repository that includes immune repertoire sequencing data.",
                "identifier": "VDJServer",
                "name": "VDJServer",
                "schema": {
                    "study_id": "identifier",
                    "study_title": "name",
                    "study_type.label": "measurementTechnique.name",
                    "study_type.id": "measurementTechnique.identifier",
                    "study_description": "description",
                    "inclusion_exclusion_criteria": "description",
                    "lab_name": "author.name",
                    "lab_address": "author.affiliation",
                    "submitted_by": "author.name",
                    "collected_by": "author.name",
                    "grants": "description",
                    "pub_ids": "citation",
                    "adc_publish_date": "datePublished",
                    "adc_update_date": "dateModified",
                    "archive_file": "distribution.conentUrl",
                    "download_url": "distribution.conentUrl",
                    "file_size": "distribution.contentSize"
                },
                "url": "https://vdj-staging.tacc.utexas.edu/community/",
            }
        }

        for source in source_info:
            if source in _meta["src"]:
                _meta["src"][source]["sourceInfo"] = source_info[source]

        return _meta
